import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import { AdminBar } from '@/components/AdminBar/AdminBar'
import Favicon from '@/components/Favicon/Favicon'
import { Footer } from '@/components/Footer/Footer'
import { InitTheme } from '@/providers/Theme/InitTheme'
import { ThemeProvider } from '@/providers/Theme/ThemeProvider'
import '@/styles/globals.scss'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html
      lang="fr"
      suppressHydrationWarning={true}
    >
      <head>
        <InitTheme />
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <ThemeProvider>
          <Favicon />
          <AdminBar />
          {children}
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  )
}
